<?php

declare(strict_types=1);
/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\NotifyPush;

/**
 * Allows apps to push messages to clients that don't have a user session.
 *
 * Sessions are identified by an id generated by this app, prefixed with the id of the app
 * that created the session. Note that this prefix is a convention to keep apps from
 * accidentally addressing each others sessions, it is not a security boundary:
 * every app on the server can push to the message queue directly and therefore to any session.
 */
interface IAnonymousSessionManager {
	/** Default lifetime of a session token */
	public const DEFAULT_TTL = 60 * 60;

	/**
	 * Maximum lifetime of a session token
	 *
	 * Sessions can't be revoked before they expire, so the lifetime is kept short.
	 * Apps that need a client to keep listening for longer should hand out a new token
	 * for the same session before the old one expires.
	 */
	public const MAX_TTL = 24 * 60 * 60;

	/**
	 * Create a new anonymous push session.
	 *
	 * The returned token needs to be handed to the client, the returned id needs to be stored
	 * by the app to be able to send messages to the session later on.
	 *
	 * Sessions are not stored server side and can not be revoked individually, the lifetime of
	 * the session is limited by $ttl instead.
	 *
	 * @param string $appId id of the app creating the session, used to namespace the session id
	 * @param int $ttl how long, in seconds, the client can keep (re)connecting with the token
	 * @throws \InvalidArgumentException if the app id or ttl is invalid
	 */
	public function createSession(string $appId, int $ttl = self::DEFAULT_TTL): AnonymousSession;

	/**
	 * Issue a new token for an existing session, keeping the session id intact.
	 *
	 * Use this to keep a client listening for longer than {@see self::MAX_TTL} without having to
	 * create a new session and update the session id stored by your app.
	 *
	 * Note that this only extends the lifetime of the session for clients that receive the new
	 * token, the previous token keeps working until it expires on its own.
	 *
	 * @param string $sessionId the id from {@see AnonymousSession::getId()}
	 * @param int $ttl how long, in seconds, the client can keep (re)connecting with the new token
	 * @throws \InvalidArgumentException if the session id or ttl is invalid
	 */
	public function renewToken(string $sessionId, int $ttl = self::DEFAULT_TTL): AnonymousSession;

	/**
	 * Send a message to an anonymous session.
	 *
	 * The message is delivered to every client currently connected with the session,
	 * messages sent while no client is connected are dropped.
	 *
	 * @param string $sessionId the id from {@see AnonymousSession::getId()}
	 * @param string $message the message type, this is what the client listens for
	 * @param mixed $body optional json serializable payload
	 */
	public function send(string $sessionId, string $message, mixed $body = null): void;
}
